---
title: "SVM"
author: "Aaron_M"
output: html_document
date: '2022-07-01'
---


```{r}

library(e1071)
library(caTools)

SVM_ <- function (dat,percent_traning,ncycles,dim) {
  
  accuracy_all <- {}
  sensitivity_all <- {}
  specificity_all <- {}
  PPV_all <- {}
  NPV_all <- {}
  
    for(k in 1:ncycles) {
    id <- sample.int(nrow(dat), floor(length(activity) * percent_traning/100))
    training <- dat[id,]
    test <- dat[-id,]
    classifier <- svm(formula = y ~ ., data = training, 
                     type = 'C-classification', kernel = 'linear')
    ncols <- dim + 1
    y_pred <- predict(classifier, newdata = test[,-ncols])

    cm <- table(test[, 4], y_pred)
    accuracy_all[k] <- (cm[1,1] + cm[2,2]) / (cm[1,1] + cm[2,2] + cm[1,2] + cm[2,1])
    sensitivity_all[k] <- cm[2,2]/(cm[2,2] + cm[2,1])
    specificity_all[k] <- cm[1,1]/(cm[1,1] + cm[1,2])
    PPV_all[k] <- cm[2,2]/(cm[2,2] + cm[1,2])
    NPV_all[k] <- cm[1,1]/(cm[1,1] + cm[2,1])
    }
  
  sensitivity_all[is.na(sensitivity_all)] <- 0
  specificity_all[is.na(specificity_all)] <- 0
  PPV_all[is.na(PPV_all)] <- 0
  NPV_all[is.na(NPV_all)] <- 0

  
  acc <- mean(accuracy_all)
  sen <- mean(sensitivity_all)
  spe <- mean(specificity_all)
  PPV <- mean(PPV_all)
  NPV <- mean(NPV_all)
  results <- data.frame(Accuracy= acc, Sensitivity= sen, Specificity= spe, PPV= PPV, NPV= NPV)
  return(results)
  
}
```

```{r}

ML.func <- function (NSC,percent_traning,ncycles,dim,act) {
  
file <- paste(NSC,c("_activity.csv"),sep="")  

raw_act <- read.csv(file=file,row.names=1)
raw_ME <- read.csv(file="MEs.csv",row.names=1)

# Remove NA
id <- which(!is.na(raw_act[,1]))
activity <<- raw_act[id,1]
MEs <- raw_ME[id,]

# Indicator
indicator <- rep(0,length(activity))
id <- which(activity>act)
indicator[id] <- 1
indicator <- as.factor(indicator)

EG_combinations_3 <- combn(MEs,dim,simplify = FALSE)
results <- data.frame(matrix(ncol = 5, nrow = length(EG_combinations_3)))
colnames(results) <- c("Accuracy", "Sensitivity", "Specificity", "PPV", "NPV")
names <- {}

for (i in 1:length(EG_combinations_3)) {
  dat <- data.frame(EG_combinations_3[[i]], y = indicator)
  cnames <- colnames(EG_combinations_3[[i]])
  names[i] <- capture.output(cat(cnames, sep= "_"))
  results[i,] <- SVM_(dat,percent_traning,ncycles)
}

 names <<- names 

row.names(results) <- names

results_sorted <- results[order(results$Accuracy, decreasing = TRUE),,drop=FALSE]
ME_labels <- data.frame(MEs = row.names(results_sorted)) 
results_sorted_xlsx <- cbind(ME_labels,results_sorted)

out <- list(results,results_sorted,results_sorted_xlsx)

return(out)

}

```


```{r}

library(tictoc)

# ML.func(dat= drugname, percent_traning= percent of data used for training, ncycles= number of cycles, dim= number of dimensions, act= activity cutoff)

tic()
NSC_287459_3D <- ML.func("NSC_287459",80,500,3,7)
NSC_732517_3D <- ML.func("NSC_732517",80,500,3,7)
NSC_778304_3D <- ML.func("NSC_778304",80,500,3,7)
NSC_764042_3D <- ML.func("NSC_764042",80,500,3,7)
NSC_759877_3D <- ML.func("NSC_759877",80,500,3,7)
NSC_768068_3D <- ML.func("NSC_768068",80,500,3,7)
NSC_764134_3D <- ML.func("NSC_764134",80,500,3,7)
toc()

save(NSC_287459_3D, NSC_732517_3D, NSC_778304_3D, NSC_764042_3D, NSC_759877_3D, NSC_768068_3D, NSC_764134_3D,file = "~/Documents/NCI-60/SVM_3D.Rdata")



```


```{r}

dfs <- list(NSC_764134_3D[[3]], NSC_778304_3D[[3]], NSC_759877_3D[[3]], NSC_764042_3D[[3]], NSC_768068_3D[[3]], NSC_732517_3D[[3]], NSC_287459_3D[[3]])

names(dfs) <- c("NSC_764134", "NSC_778304", "NSC_759877", "NSC_764042", "NSC_768068", "NSC_732517", "NSC_287459")

writexl::write_xlsx(dfs,path="~/Documents/NCI-60/SVM_3D.xlsx")

```












