---
title: "SVM"
output: html_document
date: '2022-07-01'
---

```{r}

library(e1071)
library(caTools)

raw_act <- read.csv(file="764134_activity.csv",row.names=1)
raw_ME <- read.csv(file="MEs.csv",row.names=1)

# Remove NA
id <- which(!is.na(raw_act[,1]))
activity <- raw_act[id,1]
MEs <- raw_ME[id,]

# Indicator
indicator <- rep(0,length(activity))
id <- which(activity>7)
indicator[id] <- 1
indicator <- as.factor(indicator)

SVM_ <- function (dat,percent_traning,ncycles) {
  
  accuracy_all <- {}
  sensitivity_all <- {}
  specificity_all <- {}
  PPV_all <- {}
  NPV_all <- {}
  
    for(k in 1:ncycles) {
    id <- sample.int(nrow(dat), floor(length(activity) * percent_traning/100))
    training <- dat[id,]
    test <- dat[-id,]
    classifier <- svm(formula = y ~ ., data = training, 
                     type = 'C-classification', kernel = 'linear')
    y_pred <- predict(classifier, newdata = test[,-3])

    cm <- table(test[, 3], y_pred)
    accuracy_all[k] <- (cm[1,1] + cm[2,2]) / (cm[1,1] + cm[2,2] + cm[1,2] + cm[2,1])
    sensitivity_all[k] <- cm[2,2]/(cm[2,2] + cm[2,1])
    specificity_all[k] <- cm[1,1]/(cm[1,1] + cm[1,2])
    PPV_all[k] <- cm[2,2]/(cm[2,2] + cm[1,2])
    NPV_all[k] <- cm[1,1]/(cm[1,1] + cm[2,1])
    }
  
  sensitivity_all[is.na(sensitivity_all)] <- 0
  specificity_all[is.na(specificity_all)] <- 0
  PPV_all[is.na(PPV_all)] <- 0
  NPV_all[is.na(NPV_all)] <- 0
  
  acc <- mean(accuracy_all)
  sen <- mean(sensitivity_all)
  spe <- mean(specificity_all)
  PPV <- mean(PPV_all)
  NPV <- mean(NPV_all)
  results <- data.frame(Accuracy= acc, Sensitivity= sen, Specificity= spe, PPV= PPV, NPV= NPV)
  return(results)
  
}

EG_combinations <- combn(MEs,2,simplify = FALSE)
results <- data.frame(matrix(ncol = 5, nrow = length(EG_combinations)))
colnames(results) <- c("Accuracy", "Sensitivity", "Specificity", "PPV", "NPV")
names <- {}

for (i in 1:length(EG_combinations)) {
  dat <- data.frame(EG_combinations[[i]], y = indicator)
  cnames <- colnames(EG_combinations[[i]])
  names[i] <- capture.output(cat(cnames, sep= "_"))
  results[i,] <- SVM_(dat,80,10000) #########change back to 10000
}

row.names(results) <- names

results_764134 <- results[order(results$Accuracy, decreasing = TRUE),,drop=FALSE]
ME_labels <- data.frame(MEs = row.names(results_764134)) 
results_764134_xlxs <- cbind(ME_labels,results_764134)

dat <- data.frame(EG_combinations[[88]], y = indicator)
id <- which(dat[,3] == 1)
id0 <- which(dat[,3] == 0)

plot(dat[,1],dat[,2])
points(dat[id,1], dat[id,2], col='green')
points(dat[id0,1], dat[id0,2], col='red')

```

```{r}

raw_act <- read.csv(file="778304_activity.csv",row.names=1)
raw_ME <- read.csv(file="MEs.csv",row.names=1)

# Remove NA
id <- which(!is.na(raw_act[,1]))
activity <- raw_act[id,1]
MEs <- raw_ME[id,]

# Indicator
indicator <- rep(0,length(activity))
id <- which(activity>7)
indicator[id] <- 1
indicator <- as.factor(indicator)

EG_combinations <- combn(MEs,2,simplify = FALSE)
results <- data.frame(matrix(ncol = 5, nrow = length(EG_combinations)))
colnames(results) <- c("Accuracy", "Sensitivity", "Specificity", "PPV", "NPV")
names <- {}

for (i in 1:length(EG_combinations)) {
  dat <- data.frame(EG_combinations[[i]], y = indicator)
  cnames <- colnames(EG_combinations[[i]])
  names[i] <- capture.output(cat(cnames, sep= "_"))
  results[i,] <- SVM_(dat,80,10000) #########change back to 10000
}

row.names(results) <- names

results_778304 <- results[order(results$Accuracy, decreasing = TRUE),,drop=FALSE]
ME_labels <- data.frame(MEs = row.names(results_778304)) 
results_778304_xlxs <- cbind(ME_labels,results_778304)


```

```{r}

dfs <- list(results_764134_xlxs,results_778304_xlxs)

names(dfs) <- c("NSC_764134","NSC_778304")

writexl::write_xlsx(dfs,path="~/Documents/Git_Hub/Portfolio/Internship/Machine_learning/SVM_high_corr_drugs.xlsx")

```










