---
title: "EBV project"
author: "Aaron_M"
date: "4/18/2022"
output: html_document
---

```{r}

library(stringr)

# Get file paths for each protein
dir_paths <- list.dirs("C:/Users/amoha/Documents/Brain/EBV/EBV_disorder_profiles/Disorder_results/",full.names=TRUE)[-1]

dir_names <- list.dirs("C:/Users/amoha/Documents/Brain/EBV/EBV_disorder_profiles/Disorder_results/",full.names=FALSE)[-1]

files <- {}
files <- lapply(dir_paths,list.files,pattern="\\.dat$",full.names=TRUE)

# Clean up file paths
loc_fasta.dat <- {}
for (i in 1:length(files)) { 
  loc_fasta.dat[[i]] <- grep("fasta.dat",files[[i]])
}

for (i in 1:length(files)) { 
  files[[i]] <- files[[i]][-loc_fasta.dat[[i]]]
}

loc_seq.dat <- {}
for (i in 1:length(files)) { 
  loc_seq.dat[[i]] <- grep("seq.dat",files[[i]])
}

for (i in 1:length(files)) { 
  files[[i]] <- files[[i]][-loc_seq.dat[[i]]]
}

file_names <- lapply(dir_paths,list.files,pattern="\\.dat$",full.names=FALSE)

# Clean up file names
loc_fasta.dat <- {}
for (i in 1:length(file_names)) { 
  loc_fasta.dat[[i]] <- grep("fasta.dat",file_names[[i]])
}

for (i in 1:length(file_names)) { 
  file_names[[i]] <- file_names[[i]][-loc_fasta.dat[[i]]]
}

loc_seq.dat <- {}
for (i in 1:length(file_names)) { 
  loc_seq.dat[[i]] <- grep("seq.dat",file_names[[i]])
}

for (i in 1:length(file_names)) { 
  file_names[[i]] <- file_names[[i]][-loc_seq.dat[[i]]]
}

for (i in 1:length(file_names)) {
  
file_names[[i]]<- str_sub(file_names[[i]],1,nchar(file_names[[i]])-4)
  
}




```

```{r}

# Import the data into a list of data frames

d_scores <- {}
disorder_scores <- {}

column_names <- c("RESNUM", "RES", "VLXT", "VSL2B", "VL3", "FoldIndx", "IUPred.S", "IUPred.L", "TOP.IDP", "PONDRFIT", "FITERROR", "MDP", "MDPERROR")

for (i in 1:length(dir_names)) {
  d_scores <- {}
  d_scores <- lapply(files[[i]],read.table)
  
   for (j in 1:length(d_scores)) {
   colnames(d_scores[[j]]) <- column_names
   }
  
  names(d_scores) <- file_names[[i]]
  disorder_scores[[i]] <- d_scores
  
}


names(disorder_scores) <- dir_names
   

```

```{r}

# Compute average MDP scores

MDP_list <- {}

for (i in 1:length(dir_names)) {
  MDP_temp <- {}
  for (j in 1:length(disorder_scores[[i]])) {
  MDP_temp[[j]] <-mean(disorder_scores[[i]][[j]][["MDP"]])
  }
  
  names(MDP_temp) <- file_names[[i]]
  MDP_list[[i]] <- MDP_temp
}

names(MDP_list) <- dir_names
```

```{r}

library(tidyverse)

# Reorganize data frames

MDP <- {}

for (i in 1:length(dir_names)) {
  MDP_ <- {}
  MDP_ <- t(data.frame(MDP_list[[i]]))
  MDP_ <- as.data.frame(MDP_)
  MDP_[,2] <- file_names[[i]]
  colnames(MDP_) <- c("AVG_MDP","Proteins")
  MDP_ <- MDP_[,c("Proteins","AVG_MDP")]
  MDP_ <- MDP_[order(-MDP_$AVG_MDP), , drop=FALSE]
  MDP[[i]] <- MDP_
}

names(MDP) <- dir_names



```

```{r}

library(writexl)

# Export data frames into excel

write_xlsx(MDP,"MDP.xlsx")

```



